name: atlascrm
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.69+69

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+3
  flutter_secure_storage: ^3.3.1+1
  google_sign_in: ^4.1.1
  fluttertoast: ^3.1.3
  google_maps_flutter: ^0.5.21+15
  flutter_cache_manager: ^1.1.3
  unicorndial: ^1.1.5
  flutter_launcher_icons: "^0.7.3"
  date_range_picker: ^1.0.5
  datetime_picker_formfield: ^1.0.0
  intl: ^0.16.1
  camera:
  dio:
  image:
  permission_handler: ^4.2.0+hotfix.3
  charts_flutter: ^0.9.0
  webview_flutter: ^0.3.19+9
  flutter_pusher: ^1.0.2
  flutter_google_places: ^0.2.4
  search_map_place: ^0.3.0
  table_calendar: ^2.2.3
  url_launcher: ^5.4.7
  flutter_masked_text: ^0.8.0
  searchable_dropdown: ^1.1.3
  image_picker: ^0.6.7
  multi_image_picker: ^4.6.7
  path_provider: ^1.6.10
  barcode_scan: ^3.0.1
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  xml:
  confetti: ^0.5.2
  file_picker: ^1.13.0+1
  photo_view: ^0.9.2
  flutter_pdfview: ^1.0.3+2
  maps_launcher: ^1.2.2+1
  graphql_flutter: ^3.1.0
  firebase_messaging: ^7.0.0
  loading_animations: "^2.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/a1logo_blk.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/google_logo.png
    - assets/home.png
    - assets/car.png
    - assets/a1logo_blk.png
    - assets/a1logo_wht.png
    - assets/pdf_thumbnail.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: LatoLight
      fonts:
        - asset: assets/fonts/lato/Lato-Light.ttf
    - family: LatoRegular
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
    - family: LatoBold
      fonts:
        - asset: assets/fonts/lato/Lato-Bold.ttf
    - family: InterLight
      fonts:
        - asset: assets/fonts/inter/Inter-Light-slnt=0.ttf
    - family: InterRegular
      fonts:
        - asset: assets/fonts/inter/Inter-Regular-slnt=0.ttf
    - family: InterBold
      fonts:
        - asset: assets/fonts/inter/Inter-Bold-slnt=0.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
